### ISSUE TITLE
Polish the website for an initial public beta release

### ISSUE THREAD

**Issue by jbmorley** [inseven/opolua#177]
Pulling the few remaining website issues together here to make it easier to keep a handle on what needs to be done (and make it look less overwhelming):

- [x] Get Started page -- how to view files, and how to install programs (was #107)
- [x] App Store / TestFlight description -- on the front page (was #99)
- [x] FAQ -- add known rendering details, specifically the lack of support for invert as described in #121 (was #172)

**Comment by jbmorley** [comment]
Closing as done.
